# Project: An investigation into a TMDB dataset

## Table of Contents
<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">Data Wrangling</a></li>
<li><a href="#eda">Exploratory Data Analysis</a></li>
<li><a href="#conclusions">Conclusions</a></li>
</ul>

<a id='intro'></a>
## Introduction

For this project I have chosen to look at the TMDB dataset. This data was provided as part of the Udacity Data Analysis Nanodegree and originated from [Kaggle](https://www.kaggle.com/tmdb/tmdb-movie-metadata). It was originally sourced from IMDB but was replaced after takedown request.

_Questions_:

1. Which genres are most popular from year to year?
1. What kinds of properties are associated with movies that have high revenues?

In [186]:
import pandas as pd
import numpy as np
% matplotlib inline

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
# Stop floats from displaying as scientific notation
pd.options.display.float_format = '{:20,.2f}'.format

<a id='wrangling'></a>
## Data Wrangling

### General Properties

In [187]:
# Load your data and print out a few lines. Perform operations to inspect data
# types and look for instances of missing or possibly errant data.
df = pd.read_csv('tmdb-movies.csv')

#### High level view of the dataset
----
In this section I'll take an initial view of the data - this will also include the number of rows, the datatypes and the number of non-null values in those columns. I'll also take a look at the number of unique values for those columns.

In [188]:
df.head()

id    imdb_id           popularity     budget     revenue  \
0  135397  tt0369610                32.99  150000000  1513528810   
1   76341  tt1392190                28.42  150000000   378436354   
2  262500  tt2908446                13.11  110000000   295238201   
3  140607  tt2488496                11.17  200000000  2068178225   
4  168259  tt2820852                 9.34  190000000  1506249360   

                 original_title  \
0                Jurassic World   
1            Mad Max: Fury Road   
2                     Insurgent   
3  Star Wars: The Force Awakens   
4                     Furious 7   

                                                cast  \
0  Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...   
1  Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...   
2  Shailene Woodley|Theo James|Kate Winslet|Ansel...   
3  Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...   
4  Vin Diesel|Paul Walker|Jason Statham|Michelle ...   

                                            homepage          director  \
0                      http://www.jurassicworld.com/   Colin Trevorrow   
1                        http://www.madmaxmovie.com/     George Miller   
2     http://www.thedivergentseries.movie/#insurgent  Robert Schwentke   
3  http://www.starwars.com/films/star-wars-episod...       J.J. Abrams   
4                           http://www.furious7.com/         James Wan   

                         tagline         ...           \
0              The park is open.         ...            
1             What a Lovely Day.         ...            
2     One Choice Can Destroy You         ...            
3  Every generation has a story.         ...            
4            Vengeance Hits Home         ...            

                                            overview runtime  \
0  Twenty-two years after the events of Jurassic ...     124   
1  An apocalyptic story set in the furthest reach...     120   
2  Beatrice Prior must confront her inner demons ...     119   
3  Thirty years after defeating the Galactic Empi...     136   
4  Deckard Shaw seeks revenge against Dominic Tor...     137   

                                      genres  \
0  Action|Adventure|Science Fiction|Thriller   
1  Action|Adventure|Science Fiction|Thriller   
2         Adventure|Science Fiction|Thriller   
3   Action|Adventure|Science Fiction|Fantasy   
4                      Action|Crime|Thriller   

                                production_companies release_date vote_count  \
0  Universal Studios|Amblin Entertainment|Legenda...       6/9/15       5562   
1  Village Roadshow Pictures|Kennedy Miller Produ...      5/13/15       6185   
2  Summit Entertainment|Mandeville Films|Red Wago...      3/18/15       2480   
3          Lucasfilm|Truenorth Productions|Bad Robot     12/15/15       5292   
4  Universal Pictures|Original Film|Media Rights ...       4/1/15       2947   

          vote_average  release_year           budget_adj          revenue_adj  
0                 6.50          2015       137,999,939.28     1,392,445,892.52  
1                 7.10          2015       137,999,939.28       348,161,292.49  
2                 6.30          2015       101,199,955.47       271,619,025.41  
3                 7.50          2015       183,999,919.04     1,902,723,129.80  
4                 7.30          2015       174,799,923.09     1,385,748,801.47  

[5 rows x 21 columns]

In [189]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10866 entries, 0 to 10865
Data columns (total 21 columns):
id                      10866 non-null int64
imdb_id                 10856 non-null object
popularity              10866 non-null float64
budget                  10866 non-null int64
revenue                 10866 non-null int64
original_title          10866 non-null object
cast                    10790 non-null object
homepage                2936 non-null object
director                10822 non-null object
tagline                 8042 non-null object
keywords                9373 non-null object
overview                10862 non-null object
runtime                 10866 non-null int64
genres                  10843 non-null object
production_companies    9836 non-null object
release_date            10866 non-null object
vote_count              10866 non-null int64
vote_average            10866 non-null float64
release_year            10866 non-null int64
budget_adj              1

The next cell was used to sort by different columns names (just replace the column name to get a look at the NaN data or see if there was any 0s).

In [190]:
df.sort_values(by=['vote_count'], ascending=False)

id    imdb_id           popularity     budget     revenue  \
1919   27205  tt1375666                 9.36  160000000   825500000   
4361   24428  tt0848228                 7.64  220000000  1519557910   
1386   19995  tt0499549                 9.43  237000000  2781505847   
2875     155  tt0468569                 8.47  185000000  1001921825   
4364   68718  tt1853728                 5.94  100000000   425368238   
4382   70160  tt1392170                 2.57   75000000   691210692   
5425   68721  tt1300854                 4.95  200000000  1215439994   
4363   49026  tt1345836                 6.59  250000000  1081041287   
629   157336  tt0816692                24.95  165000000   621752480   
4367   49051  tt0903624                 4.22  250000000  1017003568   
2410     603  tt0133093                 7.75   63000000   463517383   
2877    1726  tt0371746                 4.98  140000000   585174222   
1      76341  tt1392190                28.42  150000000   378436354   
4365   37724  tt1074638                 5.60  200000000  1108561013   
2633     120  tt0120737                 8.58   93000000   871368364   
2409     550  tt0137523                 8.95   63000000   100853753   
4178     278  tt0111161                 7.19   25000000    28341469   
4949     122  tt0167260                 7.12   94000000  1118888979   
630   118340  tt2015381                14.31  170000000   773312399   
0     135397  tt0369610                32.99  150000000  1513528810   
4177     680  tt0110912                 8.09    8000000   213928762   
3     140607  tt2488496                11.17  200000000  2068178225   
3911     121  tt0167261                 8.10   79000000   926287400   
3372    1771  tt0458339                 7.96  140000000   370569774   
1920   10138  tt1228705                 5.70  200000000   623933331   
6191     272  tt0372784                 5.40  150000000   374218673   
4179      13  tt0109830                 6.72   55000000   677945399   
1924   20352  tt1323594                 3.79   69000000   543513985   
4370    1930  tt0948470                 3.70  215000000   752215857   
5432   49521  tt0770828                 3.97  225000000   662845518   
...      ...        ...                  ...        ...         ...   
3357   32836  tt1254947                 0.04          0           0   
3353   14419  tt1174034                 0.03          0           0   
8829   41282  tt0209322                 0.25          0           0   
7803   30680  tt0493439                 0.07          0           0   
1093  230779  tt1621046                 0.22   10000000           0   
3335   14795  tt0972359                 0.21          0           0   
3334   41362  tt1052352                 0.08          0           0   
3330   16194  tt0996966                 0.33          0           0   
7779   16126  tt0780583                 0.11          0           0   
7773   73779  tt0934946                 0.12          0           0   
3772   73958  tt1854226                 0.21          0           0   
3596   81033  tt1874757                 0.49          0           0   
6534   27176  tt0406158                 0.17          0           0   
7754   12791  tt0494224                 0.15          0           0   
7755   42411  tt0770829                 0.14          0           0   
7756   13317  tt0454065                 0.14          0           0   
9575   40168  tt0096046                 0.12     425000           0   
1161  280922  tt3042626                 0.17          0           0   
1154  341747  tt4679082                 0.18          0           0   
3724   60302  tt1198075                 0.28    1000000           0   
7760   24786  tt0785012                 0.14          0           0   
6533   16452  tt0451021                 0.08          0           0   
7766  108176  tt1054478                 0.13          0           0   
6528   17868  tt0488664                 0.13          0           0   
7768   13710  tt1024899           

A view of the number of unique values in the columns:

In [191]:
df.nunique()

id                      10865
imdb_id                 10855
popularity              10814
budget                    557
revenue                  4702
original_title          10571
cast                    10719
homepage                 2896
director                 5067
tagline                  7997
keywords                 8804
overview                10847
runtime                   247
genres                   2039
production_companies     7445
release_date             5909
vote_count               1289
vote_average               72
release_year               56
budget_adj               2614
revenue_adj              4840
dtype: int64

#### Confirm ambiguous datatypes
----
A confirmation of the datatypes for all columns described above as 'object'.

In [192]:
print("I am imdb_id: ", type(df['imdb_id'][0]))
print("I am original_title: ", type(df['original_title'][0]))
print("I am cast: ", type(df['cast'][0]))
print("I am homepage: ", type(df['homepage'][0]))
print("I am director: ", type(df['director'][0]))
print("I am tagline: ", type(df['tagline'][0]))
print("I am keywords: ", type(df['keywords'][0]))
print("I am overview: ", type(df['overview'][0]))
print("I am genres: ", type(df['genres'][0]))
print("I am production_companies: ", type(df['production_companies'][0]))
print("I am release_date: ", type(df['release_date'][0]))

I am imdb_id:  <class 'str'>
I am original_title:  <class 'str'>
I am cast:  <class 'str'>
I am homepage:  <class 'str'>
I am director:  <class 'str'>
I am tagline:  <class 'str'>
I am keywords:  <class 'str'>
I am overview:  <class 'str'>
I am genres:  <class 'str'>
I am production_companies:  <class 'str'>
I am release_date:  <class 'str'>


#### Initial thoughts on the data so far
---
_Null Values_

While looking at null rows, I noticed that a number of columns have 0:
* popularity
* budget
* revenue
* runtime
* budget_adj
* revenue_adj

_Uniques_

For columns like 'id' and 'original_title' I would expect these to be unique all the way through. A closer inspection of these rows is needed to decide on the action.

_Datatypes_

On the face of it, the only real issue is with release_date. For proper interogation, this will need converting from a string to a datetime object.

#### Closer look at the duplications
---

This section will look at the several hundred film title dupes and the single ID duplication.

In [193]:
# create an extra column and mark a row as True where a duplicate itle is found
df['is_duplicate_title'] = df.duplicated(['original_title'])

In [194]:
# filter anything that is True
df_dupe_title_filter = df[df['is_duplicate_title'] == True]

In [195]:
df_dupe_title_filter

id    imdb_id           popularity    budget    revenue  \
1133   281778  tt3297792                 0.19         0          0   
1194   296626  tt3534842                 0.13         0          0   
1349    42222  tt0076245                 0.40         0          0   
1440     7445  tt0765010                 1.22  26000000   43318349   
1513    62320  tt1014762                 0.69         0          0   
1707    79896  tt1336006                 0.31         0          0   
1753    36465  tt0992993                 0.25         0          0   
1757    21398  tt1220213                 0.32   5000000          0   
1865   220903  tt1533395                 0.10         0          0   
2036    41505  tt1179069                 0.79  22000000     851517   
2090    42194  tt0411951                 0.60  30000000     967000   
2118    33555  tt1522835                 0.51         0          0   
2227    38568  tt1049402                 0.28     30000     617000   
2485    26177  tt0207972                 0.55         0          0   
2489    16716  tt0216621                 0.52         0          0   
2513     6522  tt0123964                 0.38  80000000   73345029   
2562    30923  tt0164993                 0.25  21000000          0   
2571    10047  tt0151137                 0.24  60000000   66976317   
2695      467  tt0242527                 0.72         0          0   
2797    11088  tt0252503                 0.27  35000000          0   
2814    11889  tt0280778                 0.22         0          0   
2892    88751  tt0373051                 2.00  45000000  101702060   
2893     8909  tt0493464                 1.98  75000000  258270008   
3272     7351  tt0903627                 0.28   6000000    1300000   
3500    64586  tt1588398                 0.85  10000000          0   
3524    63207  tt1634121                 0.76  13000000          0   
3636     9364  tt1181614                 0.41   8000000     100915   
3654    73499  tt1646980                 0.38  17000000    3696232   
3669    84404  tt1682181                 0.36   1100000          0   
3738    54320  tt1541874                 0.26    500000          0   
...       ...        ...                  ...       ...        ...   
10448    9960  tt0057261                 0.50         0          0   
10454   29056  tt0057449                 0.25         0          0   
10460   18331  tt0057372                 0.20         0          0   
10494    9542  tt0091209                 0.80         0    5844868   
10517   15392  tt0090888                 0.50         0    5738952   
10532   24913  tt0090655                 0.39   5000000          0   
10551   11415  tt0091223                 0.30   3000000          0   
10555   15698  tt0091875                 0.28         0          0   
10593   11886  tt0070608                 2.27  15000000   32056467   
10614    2926  tt0072281                 0.41         0          0   
10620   15171  tt0070016                 0.36         0          0   
10625   22307  tt0070698                 0.26    500000          0   
10628   25473  tt0070895                 0.42         0          0   
10639   26015  tt0069992                 0.14         0          0   
10642   16307  tt0070917                 0.40         0          0   
10644   29425  tt0069895                 0.11    275000          0   
10678     132  tt0065780                 0.29         0          0   
10686   51992  tt0065398                 0.08         0          0   
10691     907  tt0059113                 1.28  14000000  111721910   
10740   17529  tt0065126                 0.31         0   14250000   
10757     923  tt0077402                 1.21    650000   55000000   
10759     948  tt0077651                 1.20    300000   70000000   
10767   13333  tt0077594                 0.58         0          0   
10795  148980  tt0077215                 0.21   3000000          0   
10799   17212  tt0078067                 0.18         0          0   
10818   39995  tt0079

In [196]:
# use this cell to spot check titles for differences
df_2 = df[df['original_title'] == 'Robin Hood']
df_2.head()

id    imdb_id           popularity     budget    revenue  \
1938   20662  tt0955308                 2.12  200000000  310669540   
10593  11886  tt0070608                 2.27   15000000   32056467   

      original_title                                               cast  \
1938      Robin Hood  Russell Crowe|Cate Blanchett|Mark Strong|Oscar...   
10593     Robin Hood  Brian Bedford|Phil Harris|Peter Ustinov|Pat Bu...   

                                homepage             director  \
1938   http://www.robinhoodthemovie.com/         Ridley Scott   
10593                                NaN  Wolfgang Reitherman   

                                              tagline         ...          \
1938   Rise and rise again, until lambs become lions.         ...           
10593        Meet Robin Hood and his MERRY MENagerie!         ...           

      runtime            genres  \
1938      140            Action   
10593      83  Animation|Family   

                                    production_companies release_date  \
1938   Imagine Entertainment|Universal Pictures|Scott...      5/12/10   
10593                            Walt Disney Productions      11/8/73   

      vote_count         vote_average  release_year           budget_adj  \
1938         844                 6.10          2010       200,000,000.00   
10593        641                 6.90          1973        73,667,393.68   

               revenue_adj  is_duplicate_title  
1938        310,669,540.00               False  
10593       157,434,424.97                True  

[2 rows x 22 columns]

Upon inspection, it seems that duplicate film titles can be considered different films that have the same name.

The same process is applied for the duplicate ID. Since there is only one duplicate ID, there is no need to create a csv.

In [197]:
df['is_duplicate_id'] = df.duplicated(['id'])

In [198]:
df_dupe_id_filter = df[df['is_duplicate_id'] == True]

In [199]:
df_dupe_id_filter.head()

id    imdb_id           popularity    budget  revenue original_title  \
2090  42194  tt0411951                 0.60  30000000   967000         TEKKEN   

                                                   cast homepage  \
2090  Jon Foo|Kelly Overton|Cary-Hiroyuki Tagawa|Ian...      NaN   

              director              tagline       ...         \
2090  Dwight H. Little  Survival is no game       ...          

                                           genres    production_companies  \
2090  Crime|Drama|Action|Thriller|Science Fiction  Namco|Light Song Films   

      release_date vote_count         vote_average release_year  \
2090       3/20/10        110                 5.00         2010   

               budget_adj          revenue_adj  is_duplicate_title  \
2090        30,000,000.00           967,000.00                True   

      is_duplicate_id  
2090             True  

[1 rows x 23 columns]

Now that I have the duplicate ID (and given that the original_title duplicates appear to be different films with the same title), this is a final sense check to make sure the entire row is a duplicate.

In [200]:
df_3 = df[df['id'] == 42194]
df_3.head()

id    imdb_id           popularity    budget  revenue original_title  \
2089  42194  tt0411951                 0.60  30000000   967000         TEKKEN   
2090  42194  tt0411951                 0.60  30000000   967000         TEKKEN   

                                                   cast homepage  \
2089  Jon Foo|Kelly Overton|Cary-Hiroyuki Tagawa|Ian...      NaN   
2090  Jon Foo|Kelly Overton|Cary-Hiroyuki Tagawa|Ian...      NaN   

              director              tagline       ...         \
2089  Dwight H. Little  Survival is no game       ...          
2090  Dwight H. Little  Survival is no game       ...          

                                           genres    production_companies  \
2089  Crime|Drama|Action|Thriller|Science Fiction  Namco|Light Song Films   
2090  Crime|Drama|Action|Thriller|Science Fiction  Namco|Light Song Films   

      release_date vote_count         vote_average release_year  \
2089       3/20/10        110                 5.00         2010   
2090       3/20/10        110                 5.00         2010   

               budget_adj          revenue_adj  is_duplicate_title  \
2089        30,000,000.00           967,000.00               False   
2090        30,000,000.00           967,000.00                True   

      is_duplicate_id  
2089            False  
2090             True  

[2 rows x 23 columns]

Drop the duplicated ID row from the main dataframe:

In [201]:
df.drop_duplicates(subset=['id'],inplace=True)

### Data Cleaning (Replace this with more specific notes!)

In [202]:
# After discussing the structure of the data and any problems that need to be
#   cleaned, perform those cleaning steps in the second part of this section.

#### Drop columns:
In this section, I've decided to drop columns that are extraneous to the analysis: 
* **imdb_id**: this appears to relate to the previous IMDB data. Assumption is that this was left in by Kaggle to map the IMDB and TMDB ids together
* **popularity**: I was initially unclear what this measured. After some research on the [TMDB website](https://developers.themoviedb.org/3/getting-started/popularity) it seems that this value is derived from a number of factors and used to assist TMDB's internal search UX e.g. boosting results, etc.
* **budget** and **revenue**: since budget_adj and revenue_adj have already been normalised to 2010 levels for more direct comparision, these two columns are no longer required
* **homepage**, **tagline**, **overview** and **keywords**: seem unnecessary to include this for the type of intended analysis
* **is_duplicate_title**: is no longer necessary
* **is_duplicate_id**: is no longer necessary

In [203]:
df.drop(['imdb_id', 'popularity', 'budget', 'revenue', 'homepage', 'tagline', 'overview', 'keywords', 'is_duplicate_title', 'is_duplicate_id'], axis=1, inplace=True)

In [204]:
df.head(1)

id  original_title                                               cast  \
0  135397  Jurassic World  Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...   

          director  runtime                                     genres  \
0  Colin Trevorrow      124  Action|Adventure|Science Fiction|Thriller   

                                production_companies release_date  vote_count  \
0  Universal Studios|Amblin Entertainment|Legenda...       6/9/15        5562   

          vote_average  release_year           budget_adj          revenue_adj  
0                 6.50          2015       137,999,939.28     1,392,445,892.52

#### Update the datatypes
---

This section will look to change the release_date from a string to a datetime object.

In [205]:
df['release_date'] = pd.to_datetime(df['release_date'])

In [206]:
# check it's worked
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10865 entries, 0 to 10865
Data columns (total 13 columns):
id                      10865 non-null int64
original_title          10865 non-null object
cast                    10789 non-null object
director                10821 non-null object
runtime                 10865 non-null int64
genres                  10842 non-null object
production_companies    9835 non-null object
release_date            10865 non-null datetime64[ns]
vote_count              10865 non-null int64
vote_average            10865 non-null float64
release_year            10865 non-null int64
budget_adj              10865 non-null float64
revenue_adj             10865 non-null float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(5)
memory usage: 1.2+ MB


#### Deal with null values
---

This section will look to drop rows with null values. For **runtime**, **budget_adj** and **revenue_adj**, 0 values are also considered null.

For the first 'Genres' based question in the introduction, I will look create a dataframe that cleans out null genres, drop extraneous columns and then clean out the 0 values for budget_adj and revenue_adj. This should return me the most number of intact rows suitable for that exploration.

For the question that looks at the types of properties associcated with high revenue movies, I will wish to keep some of the dropped columns for that analysis - therefore, I will use a separate dataframe.

In [207]:
df_genres = df.copy()
df_genres.drop(['cast', 'director', 'runtime', 'production_companies', 'budget_adj', 'revenue_adj'], axis=1, inplace=True)
df_genres.head(1)

id  original_title                                     genres  \
0  135397  Jurassic World  Action|Adventure|Science Fiction|Thriller   

  release_date  vote_count         vote_average  release_year  
0   2015-06-09        5562                 6.50          2015

In [208]:
# drop NaN values - only targets genres at this stage
df_genres.dropna(axis=0, how='any', inplace=True)

Next, I want to:
* find out the individual genres that are in the genres column; and
* split these genres out into separate columns for analysis of the first question

In [209]:
df_genres_split = df_genres['genres'].str[:].str.split('|', expand=True)

In [210]:
df_genres_split.head(10)

0                1                2          3     4
0           Action        Adventure  Science Fiction   Thriller  None
1           Action        Adventure  Science Fiction   Thriller  None
2        Adventure  Science Fiction         Thriller       None  None
3           Action        Adventure  Science Fiction    Fantasy  None
4           Action            Crime         Thriller       None  None
5          Western            Drama        Adventure   Thriller  None
6  Science Fiction           Action         Thriller  Adventure  None
7            Drama        Adventure  Science Fiction       None  None
8           Family        Animation        Adventure     Comedy  None
9           Comedy        Animation           Family       None  None

In [211]:
# 
df_genres_split.groupby(0).count()

1     2    3    4
0                                    
Action           1527  1225  624  193
Adventure         564   486  266  109
Animation         371   233   92   22
Comedy           1607   705  154   35
Crime             377   259   89    9
Documentary       120    17    2    1
Drama            1741   866  278   45
Family            128    69   23    5
Fantasy           261   217  111   44
Foreign             8     7    1    1
History            43    25    8    2
Horror            662   280   54    5
Music              77    40   19    3
Mystery           122    81   29   10
Romance           177    97   36   11
Science Fiction   178   115   45    9
TV Movie           75    58   33   12
Thriller          398   252   93   18
War                54    34   15    5
Western            24    12    8    2

In [212]:
genres_list = ['Action',
               'Adventure',
               'Animation',
               'Comedy', 
               'Crime', 
               'Documentary', 
               'Drama', 
               'Family', 
               'Fantasy', 
               'Foreign', 
               'History', 
               'Horror', 
               'Music', 
               'Mystery', 
               'Romance', 
               'Science Fiction', 
               'TV Movie', 
               'Thriller', 
               'War', 
               'Western']

count = 0
for i in genres_list:
    boolean_list = []
    genre_index = genres_list[count]
    for row in df_genres['genres']:
        if genre_index in row:
            boolean_list.append(True)
        else:
            boolean_list.append(False)
    df_genres[genres_list[count]] = boolean_list
    count = count + 1

In [213]:
df_genres.head(1)

id  original_title                                     genres  \
0  135397  Jurassic World  Action|Adventure|Science Fiction|Thriller   

  release_date  vote_count         vote_average  release_year  Action  \
0   2015-06-09        5562                 6.50          2015    True   

   Adventure  Animation   ...     History  Horror  Music  Mystery  Romance  \
0       True      False   ...       False   False  False    False    False   

   Science Fiction  TV Movie  Thriller    War  Western  
0             True     False      True  False    False  

[1 rows x 27 columns]

In [214]:
df_genres.drop(['id', 'original_title', 'genres', 'release_date'], axis=1, inplace=True)

In [215]:
df_genres.head(1)

vote_count         vote_average  release_year  Action  Adventure  \
0        5562                 6.50          2015    True       True   

   Animation  Comedy  Crime  Documentary  Drama   ...     History  Horror  \
0      False   False  False        False  False   ...       False   False   

   Music  Mystery  Romance  Science Fiction  TV Movie  Thriller    War  \
0  False    False    False             True     False      True  False   

   Western  
0    False  

[1 rows x 23 columns]

In [216]:
# df_genres_test = df_genres[df_genres.release_year != 2015]
# use this later for dropping specific 0 values from budget_adj

<a id='eda'></a>
## Exploratory Data Analysis

> **Tip**: Now that you've trimmed and cleaned your data, you're ready to move on to exploration. Compute statistics and create visualizations with the goal of addressing the research questions that you posed in the Introduction section. It is recommended that you be systematic with your approach. Look at one variable at a time, and then follow it up by looking at relationships between variables.

### Research Question 1: Which genres are most popular from year to year?

In this section we will look to address the question: "Which genres are the most popular from year to year?". To approach this, we need to set some definitions.

**Most popular**: within our cleaned dataset, we have the columns 'vote_count' and 'vote_average'. These two metrics define the number of times a film received a vote by an individual and the average score out of 10 across all the individuals that voted for that film. To define a baseline for popularity, we will look at the average number of votes a film receives AND the vote_average value that is equal to or greater than the 3rd quartile.

In [217]:
df_genres.describe()

vote_count         vote_average         release_year
count            10,842.00            10,842.00            10,842.00
mean                217.82                 5.97             2,001.31
std                 576.18                 0.93                12.81
min                  10.00                 1.50             1,960.00
25%                  17.00                 5.40             1,995.00
50%                  38.00                 6.00             2,006.00
75%                 146.00                 6.60             2,011.00
max               9,767.00                 9.20             2,015.00

As we can see in the cell above, the vote_count has an average of **217.82**, while vote_average has a 3rd quartile of **6.60**. We will use these as our popularity baseline before looking at what are the _most_ popular genres from year to year.

In [218]:
df_genres = df_genres[df_genres['vote_count'] > 217.82]
df_genres = df_genres[df_genres['vote_average'] > 6.60]
df_genres

vote_count         vote_average  release_year  Action  Adventure  \
1            6185                 7.10          2015    True       True   
3            5292                 7.50          2015    True       True   
4            2947                 7.30          2015    True      False   
5            3929                 7.20          2015   False       True   
7            4572                 7.60          2015   False       True   
9            3935                 8.00          2015   False      False   
12           2854                 7.60          2015   False      False   
14           4304                 7.40          2015    True       True   
15           2389                 7.40          2015   False      False   
17           3779                 7.00          2015    True       True   
18           1495                 6.80          2015   False      False   
21           1386                 7.30          2015    True      False   
24           1545                 7.30          2015   False      False   
25           2349                 7.10          2015    True      False   
27           3833                 7.60          2015    True       True   
28           1559                 7.80          2015   False      False   
32           1264                 6.80          2015   False      False   
33           1638                 7.10          2015   False      False   
35           1520                 8.00          2015   False      False   
39            754                 7.30          2015   False      False   
40            918                 7.70          2015   False      False   
42           1035                 6.90          2015   False      False   
43           1548                 7.00          2015    True       True   
44           1221                 7.30          2015   False      False   
46           1060                 6.90          2015   False      False   
50            562                 7.10          2015   False      False   
51           1255                 7.10          2015   False      False   
52           1172                 6.70          2015   False       True   
58            867                 7.30          2015   False      False   
60           1479                 7.10          2015    True      False   
...           ...                  ...           ...     ...        ...   
10258         380                 7.00          1993   False      False   
10398         928                 7.00          1967   False       True   
10399         426                 7.50          1967   False      False   
10438         458                 6.70          1963    True       True   
10439         486                 6.70          1963   False      False   
10440         434                 7.00          1963   False      False   
10446         409                 7.50          1963   False       True   
10472        2027                 7.60          1986    True      False   
10474         650                 7.30          1986    True      False   
10476         755                 7.30          1986   False      False   
10477         792                 7.50          1986   False      False   
10480         502                 6.90          1986   False      False   
10486         354                 7.30          1986   False      False   
10489         347                 6.70          1986    True       True   
10491         363                 7.00          1986   False      False   
10492         336                 6.90          1986   False       True   
10593         641                 6.90          1973   False      False   
10594        1113                 7.20          1973   False      False   
10597         279                 7.00          1973    True      False   
10601         304                 7.70          1973   False      False   
10648         625                 7.00          1970   False       True   
10690         620               

In [230]:
# create action dataframe
df_action = df_genres[df_genres['Action'] == True].copy()
df_action.drop(['Adventure', 
                'Animation', 
                'Comedy',
                'Crime',
                'Documentary', 
                'Drama', 
                'Family', 
                'Fantasy', 
                'Foreign', 
                'History', 
                'Horror', 
                'Music', 
                'Mystery', 
                'Romance', 
                'Science Fiction', 
                'TV Movie', 
                'Thriller', 
                'War', 
                'Western'], axis=1, inplace=True)
df_action.head(1)

vote_count         vote_average  release_year  Action
1        6185                 7.10          2015    True

In [231]:
# create adventure dataframe
df_adventure = df_genres[df_genres['Adventure'] == True].copy()
df_adventure.drop(['Action', 
                'Animation', 
                'Comedy', 
                'Crime',
                'Documentary', 
                'Drama', 
                'Family', 
                'Fantasy', 
                'Foreign', 
                'History', 
                'Horror', 
                'Music', 
                'Mystery', 
                'Romance', 
                'Science Fiction', 
                'TV Movie', 
                'Thriller', 
                'War', 
                'Western'], axis=1, inplace=True)
df_adventure.head(1)

vote_count         vote_average  release_year  Adventure
1        6185                 7.10          2015       True

In [232]:
# create animation dataframe
df_animation = df_genres[df_genres['Animation'] == True].copy()
df_animation.drop(['Action', 
                'Adventure', 
                'Comedy', 
                'Crime',
                'Documentary', 
                'Drama', 
                'Family', 
                'Fantasy', 
                'Foreign', 
                'History', 
                'Horror', 
                'Music', 
                'Mystery', 
                'Romance', 
                'Science Fiction', 
                'TV Movie', 
                'Thriller', 
                'War', 
                'Western'], axis=1, inplace=True)
df_animation.head(1)

vote_count         vote_average  release_year  Animation
9        3935                 8.00          2015       True

In [111]:
# number of times a film is in the 'Crime' genre
df_crime = df_genres[df_genres['Crime'] == True]
crime_counts = df_crime['Crime'].count()
crime_counts

145

### Research Question 2  (Replace this header name!)

In [ ]:
# Continue to explore the data to address your additional research
#   questions. Add more headers as needed if you have more questions to
#   investigate.


<a id='conclusions'></a>
## Conclusions

> **Tip**: Finally, summarize your findings and the results that have been performed. Make sure that you are clear with regards to the limitations of your exploration. If you haven't done any statistical tests, do not imply any statistical conclusions. And make sure you avoid implying causation from correlation!

> **Tip**: Once you are satisfied with your work, you should save a copy of the report in HTML or PDF form via the **File** > **Download as** submenu. Before exporting your report, check over it to make sure that the flow of the report is complete. You should probably remove all of the "Tip" quotes like this one so that the presentation is as tidy as possible. Congratulations!